version: '3.8'

services:
  # The web service
  web:
    build: .
    volumes:
      - .:/app
      - static_volume:/app/static
    networks:
      - app-network
    ports:
      - "8080:8080"
    depends_on:
      - redis
    env_file:
      - .env

  # The redis service
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  static_volume:

networks:
  app-network: