# Generated by Django 4.1.13 on 2024-10-17 16:33

from django.db import migrations, models
import data_extraction_app.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=data_extraction_app.models.upload_id_file
                    ),
                ),
                (
                    "image_file",
                    models.FileField(
                        upload_to=data_extraction_app.models.upload_image_file
                    ),
                ),
                ("extracted_data", models.TextField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
